# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_hstore.fields.DictionaryField()),
                ('builder', django_hstore.fields.DictionaryField()),
            ],
        ),
    ]
