# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
    ]
